### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by achingbrain** [paulmillr/noble-secp256k1#38]
I'm seeing all sorts of CI failures related to this module:

```
Error: Error: Command failed with exit code 1: aegir build -b --no-types
Error: Cannot find module '@noble/secp256k1'
Require stack:
- /home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1.js
- /home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1-class.js
- /home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/index.js
- /home/runner/work/js-libp2p/js-libp2p/node_modules/peer-id/src/index.js
- /home/runner/work/js-libp2p/js-libp2p/src/index.js
- /home/runner/work/js-libp2p/js-libp2p/.aegir.js
- /home/runner/work/js-libp2p/js-libp2p/node_modules/lilconfig/dist/index.js
- /home/runner/work/js-libp2p/js-libp2p/node_modules/aegir/src/config/user.js
- /home/runner/work/js-libp2p/js-libp2p/node_modules/aegir/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1.js',
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1-class.js',
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/index.js',
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/peer-id/src/index.js',
    '/home/runner/work/js-libp2p/js-libp2p/src/index.js',
    '/home/runner/work/js-libp2p/js-libp2p/.aegir.js',
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/lilconfig/dist/index.js',
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/aegir/src/config/user.js',
    '/home/runner/work/js-libp2p/js-libp2p/node_modules/aegir/cli.js'
  ]
}
```

```
🚨 Build failed.

@parcel/core: Failed to resolve '@noble/secp256k1' from
'/Users/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1.js'


  /Users/runner/work/js-libp2p/js-libp2p/node_modules/libp2p-crypto/src/keys/secp256k1.js:4:22
    3 | const errcode = require('err-code')
  > 4 | const secp = require('@noble/secp256k1')
  >   |                      ^^^^^^^^^^^^^^^^^^
    5 | const { sha256 } = require('multiformats/hashes/sha2')
    6 | 
```

etc.

It looks like a fix for this was already merged in https://github.com/paulmillr/noble-secp256k1/pull/37 - can it be released please?

**Comment by paulmillr** [comment]
1.3.3

**Comment by achingbrain** [comment]
Thanks!
